spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/imooc_demo?useUnicode=true&ampcharacterEncoding=UTF-8
      username: root
      password:
  session:
    store-type: none
#  thymeleaf:
#    cache: false
#    encoding: UTF-8
#    mode: HTML
#    suffix: .html
#    prefix: classpath:/templates/
com:
  irving:
    security:
      social:
        processUrl: /qqLogin
        qq:
          providerId: callback.do
          appId: 100550231
          appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
        weixin:
          providerId: /weixin
          appId: 100550231
          appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
      CAPTCHA:
#        length: 6
#        width: 100
#        urls: /hello, /user/*, /user
      browser:
#        loginPage: /demo-login.html
#        loginType: REDIRECT
        rememberMeDuration: 1800
        signUpUrl: /demo-signup.html
server:
  port: 8077