spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/imooc_demo?useUnicode=true&ampcharacterEncoding=UTF-8
      username: root
      password:
  session:
    store-type: none
#  thymeleaf:
#    cache: false
#    encoding: UTF-8
#    mode: HTML
#    suffix: .html
#    prefix: classpath:/templates/
#com:
#  irving:
#    security:
#      browser:
#        loginPage: /demo-login.html
#loginPage: /demo-login.html