spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/imooc_demo?useUnicode=true&ampcharacterEncoding=UTF-8
      username: root
      password:
  session:
    store-type: none
#  thymeleaf:
#    cache: false
#    encoding: UTF-8
#    mode: HTML
#    suffix: .html
#    prefix: classpath:/templates/
com:
  irving:
    security:
      socail:
        qq:
          providerId: qq
          appId: wxd99431bbff8305a0
          appSecret: 60f78681d063590a469f1b297feff3c4
      CAPTCHA:
#        length: 6
#        width: 100
#        urls: /hello, /user/*, /user
      browser:
#        loginPage: /demo-login.html
#        loginType: REDIRECT
        rememberMeDuration: 1800